const express=require("express"),multer=require("multer"),fs=require("fs"),fsp=fs.promises,path=require("path"),os=require("os"),crypto=require("crypto"),{spawn}=require("child_process");
const app=express(),PORT=Number(process.env.PORT||10000),ROOT=path.join(os.tmpdir(),"html-apk-studio");
fs.mkdirSync(ROOT,{recursive:true});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:30*1024*1024,files:2}});
app.use(express.static(path.join(__dirname,"public")));
app.get("/health",(q,s)=>s.json({ok:true,service:"HTML APK Studio",androidHome:process.env.ANDROID_HOME||null}));
const jobs=new Map();
const esc=x=>String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");
function pkg(v){let a=String(v||"com.example.myapp").toLowerCase().replace(/[^a-z0-9._]/g,".").replace(/\.+/g,".").replace(/^\.+|\.+$/g,"").split(".").filter(Boolean).map(x=>x.replace(/^[^a-z]+/,"")).filter(Boolean);if(a.length<2)a=["com","example",...(a.length?a:["myapp"])];return /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(a.join("."))?a.join(".").slice(0,120):"com.example.myapp"}
function col(v,d){return /^#[0-9a-f]{6}$/i.test(v||"")?v:d}
function log(j,x,t="info"){for(const l of String(x).split(/\r?\n/).map(x=>x.trim()).filter(Boolean))j.logs.push({line:new Date().toLocaleTimeString()+"  "+l,type:t});j.logs=j.logs.slice(-160)}
function manifest(m){const map={INTERNET:"android.permission.INTERNET",CAMERA:"android.permission.CAMERA",RECORD_AUDIO:"android.permission.RECORD_AUDIO",ACCESS_FINE_LOCATION:"android.permission.ACCESS_FINE_LOCATION",ACCESS_COARSE_LOCATION:"android.permission.ACCESS_COARSE_LOCATION",READ_MEDIA_IMAGES:"android.permission.READ_MEDIA_IMAGES",POST_NOTIFICATIONS:"android.permission.POST_NOTIFICATIONS",VIBRATE:"android.permission.VIBRATE"};let p=(m.permissions||[]).filter(x=>map[x]).map(x=>`<uses-permission android:name="${map[x]}"/>`).join("\n");return `<?xml version="1.0" encoding="utf-8"?><manifest xmlns:android="http://schemas.android.com/apk/res/android">${p}<application android:theme="@style/AppTheme" android:label="${esc(m.name)}" android:icon="@drawable/app_icon" android:usesCleartextTraffic="${m.http}"><activity android:name=".MainActivity" android:screenOrientation="${m.orientation}" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>`}
function activity(m){const map={CAMERA:"android.Manifest.permission.CAMERA",RECORD_AUDIO:"android.Manifest.permission.RECORD_AUDIO",ACCESS_FINE_LOCATION:"android.Manifest.permission.ACCESS_FINE_LOCATION",ACCESS_COARSE_LOCATION:"android.Manifest.permission.ACCESS_COARSE_LOCATION",READ_MEDIA_IMAGES:"android.Manifest.permission.READ_MEDIA_IMAGES",POST_NOTIFICATIONS:"android.Manifest.permission.POST_NOTIFICATIONS"};let a=(m.permissions||[]).filter(x=>map[x]).map(x=>map[x]).join(",");return `package ${m.pkg}; import android.app.Activity;import android.os.Bundle;import android.content.Intent;import android.content.pm.PackageManager;import android.net.Uri;import android.webkit.*;import android.graphics.Color; public class MainActivity extends Activity{WebView web;ValueCallback<Uri[]> cb;static final int PICK=41;public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setBuiltInZoomControls(${m.zoom});s.setDisplayZoomControls(false);web.setBackgroundColor(Color.parseColor("${m.bg}"));web.setWebViewClient(new WebViewClient());web.setWebChromeClient(new WebChromeClient(){public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> c,FileChooserParams p){cb=c;try{startActivityForResult(p.createIntent(),PICK);return true;}catch(Exception e){cb=null;return false;}}});setContentView(web);web.loadUrl("file:///android_asset/index.html");perms();}void perms(){if(android.os.Build.VERSION.SDK_INT>=23){String[] a=new String[]{${a}};java.util.ArrayList<String> p=new java.util.ArrayList<>();for(String x:a)if(checkSelfPermission(x)!=PackageManager.PERMISSION_GRANTED)p.add(x);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),88);}}protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&cb!=null){Uri[] u=null;if(c==RESULT_OK&&d!=null&&d.getData()!=null)u=new Uri[]{d.getData()};cb.onReceiveValue(u);cb=null;}}public void onBackPressed(){if(${m.back}&&web.canGoBack())web.goBack();else super.onBackPressed();}}`}
async function write(b,r,d){let p=path.join(b,r);await fsp.mkdir(path.dirname(p),{recursive:true});await fsp.writeFile(p,d)}
async function project(b,m,html,icon){let j=m.pkg.replace(/\./g,"/");await write(b,"settings.gradle",`pluginManagement {\n    repositories { google(); mavenCentral(); gradlePluginPortal() }\n}\ndependencyResolutionManagement {\n    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)\n    repositories { google(); mavenCentral() }\n}\nrootProject.name = "${m.project}"\ninclude(":app")\n`);await write(b,"build.gradle","plugins { id 'com.android.application' version '8.6.1' apply false }");await write(b,"gradle.properties","org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8\norg.gradle.daemon=false\norg.gradle.parallel=false");await write(b,"app/build.gradle",`plugins { id 'com.android.application' } android { namespace '${m.pkg}' compileSdk 35 defaultConfig { applicationId '${m.pkg}' minSdk ${m.min} targetSdk 35 versionCode ${m.code} versionName '${esc(m.version)}' } }`);await write(b,"app/src/main/AndroidManifest.xml",manifest(m));await write(b,`app/src/main/java/${j}/MainActivity.java`,activity(m));await write(b,"app/src/main/res/values/styles.xml",`<resources><style name="AppTheme" parent="android:style/Theme.Material.Light.NoActionBar"><item name="android:statusBarColor">${m.status}</item><item name="android:navigationBarColor">${m.nav}</item><item name="android:windowLightStatusBar">${!m.dark}</item></style></resources>`);await write(b,"app/src/main/assets/index.html",html);await write(b,`app/src/main/res/drawable/app_icon.${m.iconExt||"png"}`,icon)}
function gradle(j,b){return new Promise((ok,no)=>{let c=spawn(process.env.GRADLE_BIN||"/opt/gradle/bin/gradle",["--no-daemon","--stacktrace","--console=plain","assembleDebug"],{cwd:b,env:{...process.env,GRADLE_USER_HOME:path.join(b,".gradle")},stdio:["ignore","pipe","pipe"]});let to=setTimeout(()=>{c.kill("SIGKILL");no(Error("Build timed out after 10 minutes."))},600000);let out=d=>{log(j,d);if(/> Task/i.test(String(d)))j.progress=Math.min(96,j.progress+2)};c.stdout.on("data",out);c.stderr.on("data",d=>{log(j,d,"error")});c.on("error",e=>{clearTimeout(to);no(e)});c.on("close",x=>{clearTimeout(to);x===0?ok():no(Error("Gradle exited with code "+x))})})}
app.post("/api/build",upload.fields([{name:"html",maxCount:1},{name:"icon",maxCount:1}]),async(req,res)=>{try{let h=req.files?.html?.[0];if(!h)return res.status(400).json({ok:false,error:"No HTML source received."});let id=crypto.randomBytes(8).toString("hex"),b=path.join(ROOT,id),perms=JSON.parse(req.body.permissions||"[]"),m={name:String(req.body.name||"My HTML App").slice(0,70),pkg:pkg(req.body.pkg),version:/^\d+(\.\d+){0,3}$/.test(req.body.version||"")?req.body.version:"1.0.0",code:Math.max(1,parseInt(req.body.code)||1),orientation:["portrait","landscape","unspecified"].includes(req.body.orientation)?req.body.orientation:"portrait",min:[23,26,28].includes(Number(req.body.min))?Number(req.body.min):23,bg:col(req.body.bg,"#0b1020"),status:col(req.body.status,"#0b1020"),nav:col(req.body.nav,"#000000"),dark:req.body.dark==="true",zoom:req.body.zoom==="true",back:req.body.back!=="false",http:req.body.http==="true",permissions:perms,iconExt:((req.files?.icon?.[0]?.mimetype||"image/png").split("/")[1]||"png").toLowerCase().replace("jpeg","jpg"),project:"HtmlApkStudio"+id};let j={id,status:"queued",stage:"Queued",progress:4,logs:[],base:b,apk:null,name:m.name,pkg:m.pkg};jobs.set(id,j);const fallbackIcon=fs.readFileSync(path.join(__dirname,"public","default-icon.png"));await project(b,m,h.buffer.toString("utf8"),req.files?.icon?.[0]?.buffer||fallbackIcon);j.status="building";j.stage="Building APK";j.progress=18;log(j,"Android project generated.");log(j,"Package: "+m.pkg);gradle(j,b).then(async()=>{let a=path.join(b,"app/build/outputs/apk/debug/app-debug.apk");await fsp.access(a);j.apk=a;j.status="done";j.stage="APK ready";j.progress=100;log(j,"BUILD SUCCESSFUL","success")}).catch(e=>{j.status="failed";j.stage="Build failed";log(j,e.message,"error")});res.json({ok:true,id,pkg:m.pkg})}catch(e){res.status(500).json({ok:false,error:e.message||"Server error"})}});
app.get("/api/build/:id",(q,s)=>{let j=jobs.get(q.params.id);if(!j)return s.status(404).json({ok:false,error:"Build job not found."});s.json({ok:true,id:j.id,status:j.status,stage:j.stage,progress:j.progress,logs:j.logs,name:j.name,pkg:j.pkg,download:j.status==="done"?"/api/download/"+j.id:null})});
app.get("/api/download/:id",(q,s)=>{let j=jobs.get(q.params.id);if(!j||j.status!=="done"||!j.apk||!fs.existsSync(j.apk))return s.status(404).send("APK unavailable.");s.download(j.apk,j.name.replace(/[^a-zA-Z0-9_-]/g,"_")+".apk")});
app.listen(PORT,"0.0.0.0",()=>console.log("HTML APK Studio on "+PORT));